export const WHATSAPP_NUMBER = '201128361142'

export const FACEBOOK_URL =
  'https://www.facebook.com/people/Allam-elevators-%D9%85%D8%B5%D8%A7%D8%B9%D8%AF-%D8%B9%D9%84%D8%A7%D9%85/61558660593043/?rdid=b6PbPeFBA41KDLcy&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F1ahUPV42h9%2F'

export const content = {
  en: {
    brand: 'Allam Elevators',
    brandSecondary: 'Luxury Elevator Solutions',
    langLabel: 'Language',
    nav: {
      home: 'Home',
      solutions: 'Solutions',
      design: 'Design',
      safety: 'Safety',
      projects: 'Projects',
      maintenance: 'Maintenance',
      contact: 'Contact',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      skipToContent: 'Skip to content',
    },
    hero: {
      eyebrow: 'Premium Egyptian elevator company',
      headline: 'Allam Elevators',
      subheadline: 'Luxury Elevators. Engineered for Safety. Built with Precision.',
      text: 'Premium elevator installation, maintenance, and modernization solutions for villas, residential buildings, commercial spaces, and special projects.',
      quote: 'Request a Quote',
      whatsapp: 'WhatsApp Us',
      trust: ['Safety-first engineering', 'Tailored design guidance', 'Site-specific solutions', 'Maintenance support'],
      imageAlt: 'Luxury elevator cabin with bronze and marble finishes',
    },
    floors: [
      ['G', 'Welcome', 'home'],
      ['1', 'Solutions', 'solutions'],
      ['2', 'Design', 'design'],
      ['3', 'Safety', 'safety'],
      ['4', 'Projects', 'projects'],
      ['5', 'Contact', 'contact'],
    ],
    sections: {
      solutions: {
        eyebrow: 'Elevator Solutions',
        title: 'Built for refined spaces and demanding performance.',
        text: 'From private villas to commercial projects, every solution is planned around safety, comfort, durability, and architectural harmony.',
      },
      design: {
        eyebrow: 'Design Studio',
        title: 'Material palettes that feel architectural, not generic.',
        text: 'Choose cabin finishes that match the language of the building, from warm bronze to dark marble and reflective glass.',
      },
      safety: {
        eyebrow: 'Safety & Engineering',
        title: 'Reliable operation starts before installation.',
        text: 'We focus on correct specification, technical inspection, careful installation, and scheduled maintenance for long-term confidence.',
      },
      process: {
        eyebrow: 'Process Timeline',
        title: 'A clear route from first consultation to handover.',
        text: 'Each project follows a structured workflow so owners, consultants, and contractors know what happens next.',
      },
      projects: {
        eyebrow: 'Projects Gallery',
        title: 'Elegant project previews for different building needs.',
        text: 'Placeholder project cards designed to be replaced with real installations, site photography, and case studies.',
      },
      maintenance: {
        eyebrow: 'Maintenance Plans',
        title: 'Preventive care for dependable elevator performance.',
        text: 'Flexible plans focused on inspection, reliability, preventive maintenance, and practical customer support.',
      },
      contact: {
        eyebrow: 'Contact / Quote Form',
        title: 'Tell us about your building. We will prepare the next step.',
        text: 'Send project details through WhatsApp and our team can follow up with the right technical questions.',
      },
    },
    solutions: [
      ['Villa Elevators', 'Compact, quiet, and refined elevator solutions for private homes and premium villas.'],
      ['Residential Elevators', 'Durable systems for apartments and residential buildings with everyday reliability.'],
      ['Commercial Elevators', 'Professional elevator solutions for offices, retail spaces, and mixed-use buildings.'],
      ['Panorama Elevators', 'Glass-forward designs that add visibility, elegance, and architectural presence.'],
      ['Hospital Elevators', 'Practical elevator planning for healthcare environments that require safe movement.'],
      ['Freight Elevators', 'Heavy-duty solutions for goods movement, storage areas, and operational facilities.'],
      ['Elevator Maintenance & Modernization', 'Inspection, preventive maintenance, upgrades, and modernization for existing elevators.'],
    ],
    materials: [
      ['Bronze', 'Warm metallic detail for luxury lobby aesthetics.'],
      ['Stainless Steel', 'Clean, durable finish for modern elevator cabins.'],
      ['Black Marble', 'Dark architectural texture with premium depth.'],
      ['Wood Finish', 'Natural warmth for villas and residential interiors.'],
      ['Glass', 'Open, bright, and elegant visual transparency.'],
      ['Mirror Finish', 'Reflective surfaces for spacious premium cabins.'],
    ],
    safety: [
      ['Safety Systems', 'Integrated safety components selected for dependable daily operation.'],
      ['Door Sensors', 'Sensitive door protection for smoother passenger movement.'],
      ['Emergency Operation', 'Emergency procedures and operating logic planned for safer response.'],
      ['Pre-Delivery Testing', 'Structured testing before handover to verify core functions.'],
      ['Scheduled Maintenance', 'Regular visits designed to reduce avoidable downtime.'],
      ['Specialized Technical Team', 'Technical support from people who understand installation and service needs.'],
    ],
    process: [
      ['Consultation', 'Understand the building, users, target finish, and technical expectations.'],
      ['Site Survey', 'Review dimensions, shaft conditions, power requirements, and access points.'],
      ['Design Selection', 'Select cabin style, materials, doors, controls, and project specifications.'],
      ['Supply & Installation', 'Coordinate equipment supply and professional installation on site.'],
      ['Testing & Handover', 'Test operation, safety items, and user-facing details before delivery.'],
      ['Maintenance & Follow-up', 'Continue support through inspection, maintenance, and practical guidance.'],
    ],
    filters: ['All', 'Villas', 'Residential', 'Commercial', 'Panorama', 'Maintenance'],
    projectCards: [
      ['Private Villa Elevator', 'Villas', 'Bronze cabin concept with refined residential comfort.'],
      ['Residential Building Lift', 'Residential', 'Reliable everyday movement for apartment buildings.'],
      ['Commercial Lobby Elevator', 'Commercial', 'Premium cabin styling for professional spaces.'],
      ['Panorama Glass Elevator', 'Panorama', 'Elegant transparency for architectural visibility.'],
      ['Modernization Project', 'Maintenance', 'Upgrade-focused concept for existing elevator systems.'],
      ['Signature Cabin Finish', 'Villas', 'Luxury material direction for bespoke private projects.'],
    ],
    plans: [
      {
        name: 'Basic',
        tag: 'Essential inspection',
        text: 'A practical plan for routine elevator checks and clear reporting.',
        features: ['Scheduled inspection visits', 'Basic operational checks', 'Maintenance notes', 'WhatsApp coordination'],
      },
      {
        name: 'Standard',
        tag: 'Preventive reliability',
        text: 'Balanced support for buildings that need consistent preventive maintenance.',
        features: ['Preventive maintenance visits', 'Door and control checks', 'Priority coordination', 'Clear service recommendations'],
      },
      {
        name: 'Premium',
        tag: 'Peace of mind',
        text: 'Enhanced follow-up for premium buildings and higher-usage elevators.',
        features: ['Advanced inspection routine', 'Preventive parts guidance', 'Emergency support coordination', 'Dedicated follow-up'],
      },
    ],
    contact: {
      formTitle: 'Request a quote',
      name: 'Name',
      phone: 'Phone Number',
      buildingType: 'Building Type',
      floors: 'Number of Floors',
      city: 'City',
      message: 'Message',
      submit: 'Send on WhatsApp',
      selectPlaceholder: 'Select building type',
      buildingTypes: ['Villa', 'Residential Building', 'Commercial Building', 'Hospital / Clinic', 'Freight / Service', 'Other'],
      infoTitle: 'Contact details',
      phonePlaceholder: '+20 1128361142',
      cityPlaceholder: 'Egypt',
      emailPlaceholder: 'A.allam4297@gmail.com',
      hoursPlaceholder: 'Service availability to be confirmed',
      facebook: 'Visit Facebook',
      whatsapp: 'Open WhatsApp',
      defaultMessage: 'Hello Allam Elevators, I would like to request a quote.',
    },
    footer: {
      description: 'Premium elevator installation, modernization, and maintenance solutions for refined residential and commercial spaces in Egypt.',
      quickLinks: 'Quick Links',
      services: 'Services',
      contact: 'Contact',
      copyright: 'All rights reserved.',
    },
  },
  ar: {
    brand: 'مصاعد علام',
    brandSecondary: 'حلول مصاعد فاخرة',
    langLabel: 'اللغة',
    nav: {
      home: 'الرئيسية',
      solutions: 'الحلول',
      design: 'التصميم',
      safety: 'الأمان',
      projects: 'المشاريع',
      maintenance: 'الصيانة',
      contact: 'التواصل',
      openMenu: 'فتح القائمة',
      closeMenu: 'إغلاق القائمة',
      skipToContent: 'تخطي إلى المحتوى',
    },
    hero: {
      eyebrow: 'شركة مصاعد مصرية فاخرة',
      headline: 'مصاعد علام',
      subheadline: 'تصميم فاخر، أمان موثوق، وتنفيذ دقيق',
      text: 'حلول متكاملة لتركيب وصيانة وتحديث المصاعد للفلل والمباني السكنية والمشروعات التجارية.',
      quote: 'اطلب عرض سعر',
      whatsapp: 'تواصل واتساب',
      trust: ['هندسة تركز على الأمان', 'توجيه مناسب للتصميم', 'حلول حسب طبيعة الموقع', 'دعم للصيانة'],
      imageAlt: 'كابينة مصعد فاخرة بتشطيبات برونزية ورخامية',
    },
    floors: [
      ['G', 'الرئيسية', 'home'],
      ['1', 'الحلول', 'solutions'],
      ['2', 'التصميم', 'design'],
      ['3', 'الأمان', 'safety'],
      ['4', 'المشاريع', 'projects'],
      ['5', 'التواصل', 'contact'],
    ],
    sections: {
      solutions: {
        eyebrow: 'حلول المصاعد',
        title: 'حلول تناسب المساحات الراقية ومتطلبات التشغيل.',
        text: 'من الفلل الخاصة إلى المشروعات التجارية، يتم التخطيط لكل حل حول الأمان والراحة والمتانة والتناسق المعماري.',
      },
      design: {
        eyebrow: 'استوديو التصميم',
        title: 'خامات تعطي إحساسًا معماريًا فاخرًا وليس تصميمًا تقليديًا.',
        text: 'اختر تشطيبات الكابينة بما يناسب هوية المبنى، من البرونز الدافئ إلى الرخام الأسود والزجاج العاكس.',
      },
      safety: {
        eyebrow: 'الأمان والهندسة',
        title: 'التشغيل الموثوق يبدأ قبل التركيب.',
        text: 'نركز على المواصفات الصحيحة، والفحص الفني، والتركيب الدقيق، والصيانة الدورية لثقة طويلة المدى.',
      },
      process: {
        eyebrow: 'خطوات العمل',
        title: 'مسار واضح من أول استشارة حتى التسليم.',
        text: 'كل مشروع يمر بخطوات منظمة حتى يعرف المالك والاستشاري والمقاول المرحلة التالية بوضوح.',
      },
      projects: {
        eyebrow: 'معرض المشاريع',
        title: 'نماذج عرض أنيقة لاحتياجات مختلفة من المباني.',
        text: 'بطاقات مؤقتة مصممة ليتم استبدالها لاحقًا بصور تركيبات حقيقية ودراسات حالة.',
      },
      maintenance: {
        eyebrow: 'خطط الصيانة',
        title: 'رعاية وقائية لأداء مصاعد يعتمد عليه.',
        text: 'خطط مرنة تركز على الفحص والاعتمادية والصيانة الوقائية ودعم العميل بشكل عملي.',
      },
      contact: {
        eyebrow: 'التواصل وطلب عرض سعر',
        title: 'أخبرنا عن المبنى وسنجهز الخطوة التالية.',
        text: 'أرسل تفاصيل المشروع عبر واتساب ليستطيع فريقنا متابعة الأسئلة الفنية المناسبة.',
      },
    },
    solutions: [
      ['مصاعد فلل', 'حلول هادئة وراقية ومناسبة للمنازل الخاصة والفلل الفاخرة.'],
      ['مصاعد سكنية', 'أنظمة متينة للمباني السكنية والاستخدام اليومي الموثوق.'],
      ['مصاعد تجارية', 'حلول احترافية للمكاتب والمساحات التجارية والمباني متعددة الاستخدام.'],
      ['مصاعد بانوراما', 'تصميمات زجاجية تضيف رؤية وأناقة وحضورًا معماريًا.'],
      ['مصاعد مستشفيات', 'تخطيط عملي للبيئات الطبية التي تحتاج حركة آمنة ومنظمة.'],
      ['مصاعد بضائع', 'حلول قوية لحركة البضائع والمخازن والمرافق التشغيلية.'],
      ['صيانة وتحديث المصاعد', 'فحص وصيانة وقائية وتحديثات للمصاعد القائمة حسب حالة الموقع.'],
    ],
    materials: [
      ['برونز', 'تفاصيل معدنية دافئة تناسب المداخل الفاخرة.'],
      ['ستانلس ستيل', 'تشطيب نظيف ومتين للكابائن الحديثة.'],
      ['رخام أسود', 'ملمس معماري داكن بعمق بصري فاخر.'],
      ['تشطيب خشبي', 'دفء طبيعي يناسب الفلل والمساحات السكنية.'],
      ['زجاج', 'شفافية أنيقة وإحساس أكثر اتساعًا.'],
      ['مرايا', 'أسطح عاكسة تمنح الكابينة مظهرًا أوسع وأفخم.'],
    ],
    safety: [
      ['أنظمة أمان', 'مكونات أمان مختارة لتشغيل يومي يمكن الاعتماد عليه.'],
      ['حساسات أبواب', 'حماية حساسة للأبواب لتسهيل حركة الركاب.'],
      ['تشغيل طوارئ', 'إجراءات ومنطق تشغيل للطوارئ لدعم الاستجابة الآمنة.'],
      ['اختبار قبل التسليم', 'اختبارات منظمة قبل التسليم للتأكد من الوظائف الأساسية.'],
      ['صيانة دورية', 'زيارات منتظمة تهدف لتقليل الأعطال التي يمكن تجنبها.'],
      ['فريق فني متخصص', 'دعم فني من فريق يفهم احتياجات التركيب والخدمة.'],
    ],
    process: [
      ['استشارة', 'فهم طبيعة المبنى والمستخدمين ومستوى التشطيب والمتطلبات الفنية.'],
      ['معاينة الموقع', 'مراجعة الأبعاد وحالة البئر ومتطلبات الكهرباء ونقاط الوصول.'],
      ['اختيار التصميم', 'اختيار شكل الكابينة والخامات والأبواب ولوحات التحكم والمواصفات.'],
      ['التوريد والتركيب', 'تنسيق توريد المعدات وتنفيذ التركيب باحترافية في الموقع.'],
      ['الاختبار والتسليم', 'اختبار التشغيل وعناصر الأمان والتفاصيل قبل التسليم.'],
      ['الصيانة والمتابعة', 'استمرار الدعم من خلال الفحص والصيانة والإرشاد العملي.'],
    ],
    filters: ['الكل', 'فلل', 'سكني', 'تجاري', 'بانوراما', 'صيانة'],
    projectCards: [
      ['مصعد فيلا خاصة', 'فلل', 'تصور لكابينة برونزية براحة سكنية راقية.'],
      ['مصعد مبنى سكني', 'سكني', 'حركة يومية موثوقة للمباني السكنية.'],
      ['مصعد مدخل تجاري', 'تجاري', 'تصميم كابينة فاخرة للمساحات المهنية.'],
      ['مصعد زجاجي بانوراما', 'بانوراما', 'شفافية أنيقة تمنح حضورًا معماريًا واضحًا.'],
      ['مشروع تحديث', 'صيانة', 'تصور لتحديث مصعد قائم حسب احتياج الموقع.'],
      ['تشطيب كابينة مميز', 'فلل', 'اتجاه فاخر للخامات في المشروعات الخاصة.'],
    ],
    plans: [
      {
        name: 'أساسية',
        tag: 'فحص أساسي',
        text: 'خطة عملية للفحص الدوري للمصعد وتقديم ملاحظات واضحة.',
        features: ['زيارات فحص مجدولة', 'مراجعة تشغيل أساسية', 'ملاحظات صيانة', 'تنسيق عبر واتساب'],
      },
      {
        name: 'قياسية',
        tag: 'اعتمادية وقائية',
        text: 'دعم متوازن للمباني التي تحتاج صيانة وقائية منتظمة.',
        features: ['زيارات صيانة وقائية', 'فحص الأبواب والتحكم', 'تنسيق بأولوية', 'توصيات خدمة واضحة'],
      },
      {
        name: 'مميزة',
        tag: 'راحة بال',
        text: 'متابعة أعلى للمباني الفاخرة والمصاعد ذات الاستخدام الأكبر.',
        features: ['روتين فحص متقدم', 'إرشاد لقطع الغيار الوقائية', 'تنسيق دعم للطوارئ', 'متابعة مخصصة'],
      },
    ],
    contact: {
      formTitle: 'طلب عرض سعر',
      name: 'الاسم',
      phone: 'رقم الهاتف',
      buildingType: 'نوع المبنى',
      floors: 'عدد الأدوار',
      city: 'المدينة',
      message: 'الرسالة',
      submit: 'إرسال عبر واتساب',
      selectPlaceholder: 'اختر نوع المبنى',
      buildingTypes: ['فيلا', 'مبنى سكني', 'مبنى تجاري', 'مستشفى / عيادة', 'بضائع / خدمة', 'أخرى'],
      infoTitle: 'بيانات التواصل',
      phonePlaceholder: '+20 100 000 0000',
      cityPlaceholder: 'مصر',
      emailPlaceholder: 'info@example.com',
      hoursPlaceholder: 'مواعيد الخدمة يتم تأكيدها',
      facebook: 'زيارة فيسبوك',
      whatsapp: 'فتح واتساب',
      defaultMessage: 'مرحبًا مصاعد علام، أريد طلب عرض سعر.',
    },
    footer: {
      description: 'حلول تركيب وتحديث وصيانة مصاعد فاخرة للمساحات السكنية والتجارية الراقية في مصر.',
      quickLinks: 'روابط سريعة',
      services: 'الخدمات',
      contact: 'التواصل',
      copyright: 'جميع الحقوق محفوظة.',
    },
  },
}
